/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:fd205de8-ca8d-4fa2-bc24-13c3165832ea",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Yyb3hia44",
    "aws_user_pools_web_client_id": "5vh89bc5erdpudcbmjq7b48gm3",
    "oauth": {}
};


export default awsmobile;
